# Package Overview
package_name: bike_model

# Data Files
training_data_file: bike-sharing-dataset.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: cnt

pipeline_name: bike_pipe
pipeline_save_file: bike__model_output_v

features:      # final features to be use
  - dteday
  - season
  - hr 
  - holiday 
  - weekday
  - workingday   
  - weathersit   
  - temp       
  - atemp
  - hum
  - windspeed
  - Year                  # Derived from dteday column
  - Month                 # Derived from dteday column
  - casual
  - registered

unused_fields:  # Features to drop before pipeline
  - dteday
  - casual
  - registered

# Features inside processing pipeline

weekday_var: weekday  # first imputatation , then --> Mappeing
weathersit_var: weathersit

cols_delete:
  - dteday
  - casual
  - registered

mapping_dict:
  Year: 
    '2011': 0
    '2012': 1
  Month:
    January: 0
    February: 1
    December: 2
    March: 3
    November: 4
    April: 5
    October: 6
    May: 7
    September: 8
    June: 9
    July: 10
    August: 11
  season:
    spring: 0
    winter: 1
    summer: 2
    fall: 3
  weathersit:
    Heavy Rain: 0
    Light Rain: 1
    Mist: 2
    Clear: 3
  holiday: 
    Yes: 0
    No: 1
  workingday: 
    No: 0
    Yes: 1
  hr: 
    4am: 0 
    3am: 1
    5am: 2
    2am: 3
    1am: 4
    12am: 5
    6am: 6
    11pm: 7
    10pm: 8
    10am: 9
    9pm: 10
    11am: 11
    7am: 12
    9am: 13
    8pm: 14
    2pm: 15
    1pm: 16
    12pm: 17
    3pm: 18
    4pm: 19
    7pm: 20
    8am: 21
    6pm: 22
    5pm: 23
       
num_cols:
  - temp
  - atemp
  - hum
  - windspeed

onehot_cols:
  - weekday
  
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 150
max_depth: 10

